### ISSUE TITLE
Query about Orbit rpc performance

### ISSUE THREAD

**Issue by amit2103** [electronicarts/orbit#116] opened 2015-12-01 07:59 UTC
Hello, I wanted to check the RPC call performance of Orbit. I saw that for things like a hello world, it takes 1 MS to make a request-reply. However other Actor frameworks does it in significantly less. 

I want to know is it possible to configure Orbit to use things like Netty? Also Lets say I am in JVM 1 (in a 2 JVM cluster) and I am trying to find teh actor "hello", so if I make multiple calls to "hello", can I request somethings like Co-location. I think a RPC call in this scenario will be wasteful, may be local calls will suffice. 

I am sure with time this optimizations will be done in Orbit, I myself was thinking of storing the orbit actor states in Infinsipan grid. It will be nice if you can clarify on these.

**Comment by DanielSperry** [comment] 2015-12-01 13:44
Hi @amit2103, 

It's possible to replace the orbit network, the distributed directory, the serialization, and the persistence
by implementing ClusterPeer (the default is jgroups + infinispan), MessageSerializer, and StorageExtension.

However, first things first:
- How did you test this? 
- Over how many requests? 

For local calls there are three standard scenarios.
- Actors annotated with `@Stateless` will be instantiated in the same node as the caller. That's because there can be many copies of the same stateless actor.
- If there is a single caller that usually calls that actor and for some reason the actor can't be `@Stateless` you can add `@PreferLocalPlacement` to the actor, the system will try to instantiate the actor in the same node as the caller.
- Nodes can be heterogeneous. Meaning that certain nodes can be told to handle only a sub set of the actor classes. A clever grouping of actor classes can force a certain communication pattern between the nodes.

**Comment by amit2103** [comment] 2015-12-01 13:48
@DanielSperry  I tested over 1 million requests 5 times to get that latency. 
The Stateless workers are very useful. But I was testing with Stateful actors. 
If I select the appropiate node, lets say node1 which contains Actor A, and make a call for Actor A from Node 1 then does Orbit make a RPC call or a local method call?

Thansk for the pointers I will look into them.

Regards

**Comment by DanielSperry** [comment] 2015-12-01 16:04
Hi @amit2103,

I need more info on your test:
- how many nodes?
- are all messages to the same actor (same class and object Id)?
  (If each message is for a completely different actor they will cause a new activation every time, that can be expensive)
- are you sending the messages and waiting the return? or sending a batch and waiting for the batch to complete?

Orbit is not yet optimizing local calls so they might be as slow as networked messages. Local calls are currently serialized and sent to the cluster peer (jgroups), They are bounced back but that takes. 
So if you are using a single node cluster for your test and comparing with something else that optimize local calls orbit might look slower.

To handle only a subset of actor classes per node you need either:
- not to have the actor implementations of all the actor in the node class path. The node will only serve the actors it knows about.
- or to set the Stage with an `ActorFinder` that knows only a subset of the actor implementations.

**Comment by amit2103** [comment] 2015-12-01 16:13
@DanielSperry  Thanks for the replies.

I tested with a two node cluster. All messages are to the same actor  and yes I wait for the response. Those parts Orbit does reasonably well. But I think (and as you confirmed), the latency is due to Orbit doing a RPC . I also felt that Orbit does not make a local call even when the node is the same for  the caller and callee. Can this be taken up as an optimization by the Orbit team? I think this might bring down reply times drastically for usecases like mine. (from milli seconds to micros I believe) I will be glad to contribute, but this seems to be a bit too much on the Orbit internals. If however you can guide me , in case you guys do not want to take this up, I can give it a shot.

**Comment by DanielSperry** [comment] 2015-12-01 16:50
Hi @amit2103,

More questions:
- With a two node cluster, who was sending the messages?
- Were you sending messages from both nodes?

About the optimization. Orbit handes rpc in a pipeline:
![image](https://cloud.githubusercontent.com/assets/2395112/11506706/b6fe6d6c-981e-11e5-8855-a28d033ae59e.png)
Each member of the pipeline is a Handler and has a `write` and a `onRead` method.

After `Messaging` you have the target address and the request-response handling, The next Handler could just short-circuit the `write` calling `fireRead` in the context. The code would look like this.
```java
public class LocalMessagerHandler extends NamedPipelineExtension {
    public LocalMessagerHandler()   {
        super("local-message-handler", null, DefaultHandlers.MESSAGING);
    }

    @Override
    public Task write(final HandlerContext ctx, final Object msg) throws Exception  {
        if (msg instanceof Message) {
            Message message = (Message) msg;
            if (todo_checkIfTheMessageIsLocal(message.getToNode()))  {
                message.setPayload(todo_cloneTheMessagePayload(message.getPayload()));
                // short circuits the message back
                ctx.fireRead(message);
                return Task.done();
            }
        }
        return ctx.write(msg);
    }
}
```
It's important to clone the message arguments to avoid concurrency problems.
You can add the new handler in Stage.start(), Look for the variable cacheManager over there for an example.

**Comment by amit2103** [comment] 2015-12-01 17:10
@DanielSperry  
I tried two scenarios 1) I was sending the message from an external node (Websocket client). 
2) I tried sending from two nodes.

Thanks for the excellent doc. This is not only helpful but is also helpful in understanding how Orbit works. I can understand that Orbit's current architecture should enable this optimization  easily.

**Comment by DanielSperry** [comment] 2015-12-01 18:29
Hi @amit2103,

I'd be interested in running your tests to profile Orbit.
Let me know if you can share it.

if your handler has a pointer to the Stage, you can do:
```java
localAddress = stage.getHosting().getNodeAddress()
return localAddress.equals(message.getToAddress());
```

**Comment by DanielSperry** [comment] 2015-12-01 20:55
Hey @amit2103, 

I found that the request latency for single node requests is  ≈ 100 micro seconds.

These are the results of my micro benchmark tests 
(using jgroups, single node, no local message optimization).

  |Mode  |Cnt      |Score     |Error  |Units
------|------|------|------|------|------
**Mutiple actors multiple threads**|||||
SingleNodeBenchmark.requestThroughput  |thrpt | 100  | 68378.175| ± 818.607  |ops/s
**Single actor single thread**|||||
SingleNodeBenchmark.requestLatency      |avgt  | 100   |  ≈ 10⁻⁴       |      |s/op


Using [OpenJDK JMH](http://openjdk.java.net/projects/code-tools/jmh/)
Test source here: [DanielSperry/orbit/actors/test/benchmarks](https://github.com/DanielSperry/orbit/blob/ca10e50405a4f70be0fdcea87b199168d20646b2/actors/test/benchmarks/src/main/java/com/ea/orbit/actors/test/SingleNodeBenchmark.java)
I'm running the tests from Intellij using the [JMH plugin](https://plugins.jetbrains.com/plugin/7529?pr=)

**Comment by DanielSperry** [comment] 2015-12-02 03:39
I did some more benchmarks, in a slower computer, but with the message loopback in place.

All local requests; and the loopback lets them skip network and serialization:
Result: 246 K RPS, ≈ 10 micro second response time

Loopback tests  |Mode  |Cnt      |Score     |Error  |Units
------|------|------|------|------|------
**Mutiple actors multiple threads**|||||
SingleNodeBenchmark.requestThroughput  |thrpt  |100  |246672.212 | ± 5778.746  |ops/s
**Single actor single thread**|||||
SingleNodeBenchmark.requestLatency      |avgt  |100     | ≈ 10⁻⁵          |    |s/op

Test log: [raw-result-loopback.txt](https://github.com/electronicarts/orbit/files/49356/raw-result-loopback.txt)

I must reinforce in this thread that these results are interesting but that
orbit-actors' goal is horizontal scalability 
so what really matters is the RPS curve as more machines are added to a cluster.

**Comment by amit2103** [comment] 2015-12-02 06:40
Hello @DanielSperry , Sorry for the late reply and many thanks for the fast answers. I used Orbit container. Does that add some extra overhead by the by?  I inspected the code but it seemed pretty light weight to me. I will go back and use Stages and add message loopbacks. This should do the trick for me (10MS is excellent ) .

However I still think Orbit should automatically try to detect that the client and the Actor are in the same machine and do this. And as you explained it can be done easily. In my case I will have multiple grids, based on some logic in the frontend I will always try to route to the node which has the actor. But if Orbit makes the RPC it wont help. Note I cannot add the loopback in this case. So I think the proposed changes, are nice to have optimizations. That will increase throughput per node drastically.

I was initially drawn towards Orbit due to its excellent Horizantal Scalability. I am considering writing a StorageExtension for memory grids due to this. However my application is extremely latency sensitive. I wanted to propose this in our org. But wanted to do these tests.

**Comment by DanielSperry** [comment] 2015-12-02 08:17
Hi @amit2103,

I'm glad you are considering writing an Orbit extension. 
The Container is pretty light indeed.

The `MessageLoopback` is now part of the Stage, no extra configuration required to use it.
Thanks for bring that up.

**Comment by amit2103** [comment] 2015-12-02 09:58
@DanielSperry , Thanks.

Last question, may be I misunderstood this. Is the local message optimization present now or will you add this in your upcoming releases?

**Comment by johnou** [comment] 2015-12-02 10:18
@amit2103 it has been committed to master branch, you can either compile a snapshot from source or wait for the next release.

**Comment by amit2103** [comment] 2015-12-02 10:20
Cool...If Orbit automatically detects that the Actor and the callee are both in the same JVm and makes a local call, this will solve my problem. Great.

Thanks Again.

**Comment by DanielSperry** [comment] 2015-12-02 15:20
Cool. I'm closing the issue then.

**Closed by DanielSperry** 2015-12-02 15:20 UTC

**Comment by DanielSperry** [comment] 2015-12-11 21:48
Benchmarks from 2015-12-11:

```
Benchmark                                         Mode  Cnt        Score       Error  Units
SingleNodeBenchmark.requestThroughput            thrpt  100  2492004.597 ± 24403.027  ops/s
SingleNodeBenchmark.avgRequestTime_batched        avgt  100        1.634 ±     0.009  us/op
SingleNodeBenchmark.avgRequestTime_singleThread   avgt  100        4.506 ±     0.040  us/op

# Processor: i7-5820K 3.3GHz 64GB RAM (Windows 7)
# CPU count: 12 
# JMH 1.11.2 (released 43 days ago)
# VM version: JDK 1.8.0_66, VM 25.66-b18
```

**Comment by amit2103** [comment] 2015-12-12 16:45
@DanielSperry  Thanks for updating the tests. Your test rig is infinitely more powerful than mine (Fx 8350 , 16 GB ram) . Did you do a request-reply, or a simple request?

**Comment by DanielSperry** [comment] 2015-12-12 17:29
@amit2103, Each sample generates one request message and one response message (one reply):

check [SingleNodeBenchmark.java](https://github.com/electronicarts/orbit/blob/master/actors/test/benchmarks/src/main/java/com/ea/orbit/actors/test/SingleNodeBenchmark.java).

Each sample (each <i>op</i>eration) is single a call to: 
```
        @Override
        public Task<String> sayHello(final String greeting)
        {
            return Task.fromValue(greeting);
        }
```
To handle one such call orbit-actors have to issue one request message and one response message.

**Comment by amit2103** [comment] 2015-12-12 18:07
@DanielSperry  Thanks for the clarification. What is us/op? The throughput seems extremely impressive.

**Comment by JoeHegarty** [comment] 2015-12-13 01:17
Tried running it on my machine just to see the difference.
I have a Skylake CPU and am using DDR4, seems I squeezed out a little extra performance.

Benchmarks from 2015-12-12:

```
Processor: i7-6700 3.40GHz 32GB RAM (Windows 10)
CPU Count: 8
JMH 1.11.2 (released 44 days ago)
VM version: JDK 1.8.0_66, VM 25.66-b18
```
```java

Benchmark                                         Mode  Cnt        Score       Error  Units
SingleNodeBenchmark.requestThroughput            thrpt  100  2674034.764 ± 30701.044  ops/s
SingleNodeBenchmark.avgRequestTime_batched        avgt  100        1.314 ±     0.005  us/op
SingleNodeBenchmark.avgRequestTime_singleThread   avgt  100        4.272 ±     0.021  us/op
```

**Comment by DanielSperry** [comment] 2015-12-13 03:00
@JoeHegarty, It might also be due one optimization or two added since my last <i>published</i> test :)

@amit2103 us/op = microseconds per operation

**Comment by amit2103** [comment] 2015-12-13 09:56
I did the tests, I can say that RAM Frequency does play its part, with a comparable CPU.  Anyways the performance is now truly impressive.

**Comment by johnou** [comment] 2015-12-13 10:08
@benjchristensen this issue might interest you.

**Comment by amit2103** [comment] 2015-12-16 10:14
Just to re affirm my understanding if I send a message to an actor in the same JVM it will now be a local message call , with the latest release 0.6x ?

Regards

**Comment by JoeHegarty** [comment] 2015-12-16 15:28
Yes, that's correct. There are some additional optimizations coming in 0.6.2 as well

**Comment by amit2103** [comment] 2015-12-18 15:41
I have one observation. It appears to me that Orbit clones the messages. Is it correct? If so, is it necessary to clone the message in case of Local messages, why not pass the same message. It should be the responsibility of the client dev's to pass immutable messages.

**Comment by DanielSperry** [comment] 2015-12-18 21:39
Hi @amit2103,

### About cloning

Only local messages are cloned. 
Remote messages are serialized, the result is the same.

That's to ensure isolation between actors.
Otherwise it would be possible that one actor would contaminate another actor state.
Or change arguments before they are received.

For example: one actor could send an ArrayList to another actor. 
And then change the contents of the list.
This leads to all sorts of unexpected behaviours.

There are possible optimizations for instance Orleans lets the application mark certain objects as Immutable.

### LocalPlacement  
LocalPlacement can be minimize remote messages.
Just be sure to validate that you don't get all the actors migrating to the same node as a consequence of your application topology.

**Comment by amit2103** [comment] 2015-12-19 06:29
@DanielSperry I understand remote messages are serialized. There is no other way to communicate to remote nodes. I also understand that you seem to be using Kyro. Thats okay too.

But cloning local messages seems to be a bit too much. I think it can be avoided. Because it is a needless performance hit. I suggest you bring a config which allows the dev's to mark the messages as immutable and hence avoid copying.
