### ISSUE TITLE
StatelessWorker Exception

### ISSUE THREAD

**Issue by Fiurgeist** [electronicarts/orbit#86] opened 2015-07-22 16:27 UTC
As discussed in Gitter:
see https://github.com/Fiurgeist/OrbitIssue

There you can find a unit test which doesn't make a lot of sense as it is, because I streamlined it to focus on the issue.
It's basically just a for loop which calls a StatelessWorker a 100 times and in that actor another StatelessWorker is called.
And every 10th or so run of the test I get this exception:

```
Jul 22, 2015 5:06:12 PM com.ea.orbit.concurrent.ExecutorUtils lambda$newScalingThreadPool$0
Uncaught Exception
java.lang.Error: Error loading class: null
    at com.ea.orbit.actors.runtime.Execution.classForName(Execution.java:776)
    at com.ea.orbit.actors.runtime.Execution.classForName(Execution.java:762)
    at com.ea.orbit.actors.runtime.Execution.access$300(Execution.java:93)
    at com.ea.orbit.actors.runtime.Execution$Activation.getOrCreateInstance(Execution.java:432)
    at com.ea.orbit.actors.runtime.Execution.executeMessage(Execution.java:989)
    at com.ea.orbit.actors.runtime.Execution.lambda$handleOnMessageReceived$24(Execution.java:912)
    at com.ea.orbit.actors.runtime.Execution$$Lambda$55/2071701248.get(Unknown Source)
    at com.ea.orbit.actors.runtime.ExecutionSerializer.lambda$offerJob$32(ExecutionSerializer.java:116)
    at com.ea.orbit.actors.runtime.ExecutionSerializer$$Lambda$56/619859981.run(Unknown Source)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.ea.orbit.actors.runtime.Execution.classForName(Execution.java:770)
    ... 13 more
```

**Comment by DanielSperry** [comment] 2015-07-22 19:53
This means the concreteClassName was not initialized.

I have two hypotheses: 
  1. Hosting not calling canActivate in the target node. Unlikely since some invocations work...
  2. Some race condition or worse with Execution.descriptorMapByInterface (this should be a concurrent map!)


But I couldn't reproduce the issue with your example.
I've increased the test count to 4000 and 100.000 to no avail.
(with 1.000.000 I start getting execution refused...)

```java
public class WorkerTest extends ActorBaseTest
{
    private static final int LENGTH = 100_000;

    @Test
    public void testSequence() throws ExecutionException, InterruptedException
    {
        createStage();
        List<Task> list = new ArrayList<>();
        for (int i = 0; i < LENGTH; ++i)
        {
            Actor.getReference(ListAActor.class, "listA").add("" + i);
        }

        list.forEach(t -> t.join());
        Assert.assertEquals(true, true);
    }
}
```

@Fiurgeist Could you please test this patch in your environment:

```
Index: orbit-public/actors/stage/src/main/java/com/ea/orbit/actors/runtime/Execution.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- orbit-public/actors/stage/src/main/java/com/ea/orbit/actors/runtime/Execution.java	(revision c5d02cf9f76e73276ad18f372298e8f91320df36)
+++ orbit-public/actors/stage/src/main/java/com/ea/orbit/actors/runtime/Execution.java	(revision )
@@ -81,6 +81,7 @@
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.ConcurrentHashMap;
 import java.util.concurrent.ConcurrentLinkedDeque;
+import java.util.concurrent.ConcurrentMap;
 import java.util.concurrent.ExecutionException;
 import java.util.concurrent.ExecutorService;
 import java.util.concurrent.ForkJoinTask;
@@ -96,8 +97,8 @@
     private static final Logger logger = LoggerFactory.getLogger(Execution.class);
     private final String runtimeIdentity;
     private ActorClassFinder finder;
-    private Map<Class<?>, InterfaceDescriptor> descriptorMapByInterface = new HashMap<>();
-    private Map<Integer, InterfaceDescriptor> descriptorMapByInterfaceId = new HashMap<>();
+    private ConcurrentMap<Class<?>, InterfaceDescriptor> descriptorMapByInterface = new ConcurrentHashMap<>();
+    private ConcurrentMap<Integer, InterfaceDescriptor> descriptorMapByInterfaceId = new ConcurrentHashMap<>();
     private Map<EntryKey, ReferenceEntry> localActors = new ConcurrentHashMap<>();
     private Map<EntryKey, ActorObserver> observerInstances = new MapMaker().weakValues().makeMap();
     // from implementation to reference
@@ -810,8 +811,8 @@
             interfaceDescriptor.isObserver = ActorObserver.class.isAssignableFrom(aInterface);
             interfaceDescriptor.factory = dynamicReferenceFactory.getFactoryFor(aInterface);
             interfaceDescriptor.invoker = (ActorInvoker<Object>) interfaceDescriptor.factory.getInvoker();
-            descriptorMapByInterface.put(aInterface, interfaceDescriptor);
-            descriptorMapByInterfaceId.put(interfaceDescriptor.factory.getInterfaceId(), interfaceDescriptor);
+            descriptorMapByInterface.putIfAbsent(aInterface, interfaceDescriptor);
+            descriptorMapByInterfaceId.put(interfaceDescriptor.factory.getInterfaceId(), descriptorMapByInterface.get(aInterface));
         }
         return interfaceDescriptor;
     }
```

**Comment by Fiurgeist** [comment] 2015-07-23 08:55
@DanielSperry seems to be fixed, can't reproduce it any more

**Comment by johnou** [comment] 2015-07-23 09:07
I addressed a few issues in the above patch, result from putIfAbsent should be returned or the race condition is still present and there was a redundant get on descriptorMapByInterface.

**Comment by DanielSperry** [comment] 2015-07-23 13:19
Cool :) thanks guys!

**Comment by Fiurgeist** [comment] 2015-07-23 16:05
unfortunately it just happened again :/
seems to be less frequent though

```
Jul 23, 2015 5:50:41 PM com.ea.orbit.concurrent.ExecutorUtils lambda$newScalingThreadPool$6
Uncaught Exception
java.lang.Error: Error loading class: null
	at com.ea.orbit.actors.runtime.Execution.classForName(Execution.java:776)
	at com.ea.orbit.actors.runtime.Execution.classForName(Execution.java:762)
	at com.ea.orbit.actors.runtime.Execution.access$300(Execution.java:93)
	at com.ea.orbit.actors.runtime.Execution$Activation.getOrCreateInstance(Execution.java:432)
	at com.ea.orbit.actors.runtime.Execution.executeMessage(Execution.java:996)
	at com.ea.orbit.actors.runtime.Execution.lambda$handleOnMessageReceived$23(Execution.java:919)
	at com.ea.orbit.actors.runtime.Execution$$Lambda$54/519927364.get(Unknown Source)
	at com.ea.orbit.actors.runtime.ExecutionSerializer.lambda$offerJob$1(ExecutionSerializer.java:116)
	at com.ea.orbit.actors.runtime.ExecutionSerializer$$Lambda$55/1043499521.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.ea.orbit.actors.runtime.Execution.classForName(Execution.java:770)
	... 13 more
```

**Comment by DanielSperry** [comment] 2015-07-23 18:26
this test is really good at reproducing the problem:

```
public class WorkerTest extends ActorBaseTest
{

    @StatelessWorker
    public interface MyActor extends Actor
    {
        Task<Void> ping();
    }

    public static class MyActorImpl extends AbstractActor implements MyActor
    {
        @Override
        public Task<Void> ping()
        {
            return Task.done();
        }
    }

    @Test
    public void testSequence() throws ExecutionException, InterruptedException
    {
        Stage stage = createStage();
        MyActor ref = Actor.getReference(MyActor.class, clusterName);
        List<Task<Void>> list = IntStream.range(1, 10)
                .parallel()
                .mapToObj(i -> ref.ping())
                .collect(Collectors.toList());
        Task.allOf(list).join();
        stage.stop().join();
    }
}
```

**Comment by DanielSperry** [comment] 2015-07-23 19:09
I'd say the main problem was in the ClassPathSearch.findImplementation  where class descriptors where concurrently initialized leading to the actor implementation not being found. 

Involved parts in the bug:

   - Execution.getDescriptor(Class):  fixed by @johnou
   - Execution.canActivateActor: when called concurrently could call finder.findActorImplementation multiple times (in parallel).
   - ClassPathSearch.findImplementation modifies ClassInfos during the search leading to parallel search problems. This was fixed by synchronizing the search (a potential optimization is synchronizing only ClassPathSearch.getClassInfo at the point were it loads the info...)

**Closed** 2015-07-23 19:11 UTC
Labels: bug
